<?php
// Register widget zones
if ( !function_exists('register_sidebars') )
	return;
/* ------- PEBC custom widget areas ------- */
	register_sidebar(array('name' => 'FirstWidgetAll','id' => 'FirstWidgetAll','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'LastWidgetAll','id' => 'LastWidgetAll','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'AboutUsWidget','id' => 'AboutUsWidget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'educationeventswidget','id' => 'educationeventswidget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'ee-stem-widget','id' => 'ee-stem-widget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'ee-literacy-widget','id' => 'ee-literacy-widget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'ee-coaching-widget','id' => 'ee-coaching-widget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'ee-lab-widget','id' => 'ee-lab-widget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'ee-leadership-widget','id' => 'ee-leadership-widget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'publicationswidget','id' => 'publicationswidget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'staffwidget','id' => 'staffwidget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'professionallearningwidget','id' => 'professionallearningwidget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));
	register_sidebar(array('name' => 'researchandpracticewidget','id' => 'researchandpracticewidget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));

	/* ------- PEBC custom widget areas End ------- */
/*	register_sidebar(array('name' => 'PrimaryLeft1','id' => 'PrimaryLeft1','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="postTitle">','after_title' => '</h2>',)); */
	register_sidebar(array('name' => 'PrimaryLeft2','id' => 'PrimaryLeft2','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="postTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'PrimaryMid1','id' => 'PrimaryMid1','before_widget' => '<div id="%1$s" class="widget midColPost %2$s">','after_widget' => '</div>','before_title' => '<h2 class="postTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'PrimaryMid2','id' => 'PrimaryMid2','before_widget' => '<div id="%1$s" class="widget midColPost %2$s">','after_widget' => '</div>','before_title' => '<h2 class="postTitle">','after_title' => '</h2>',));	
/*	register_sidebar(array('name' => 'PrimaryRight1','id' => 'PrimaryRight1','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<span class="titleCatName">','after_title' => '</span>',));	
	register_sidebar(array('name' => 'PrimaryRight2','id' => 'PrimaryRight2','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<span class="titleCatName">','after_title' => '</span>',));	
	register_sidebar(array('name' => 'SecondaryLeft1','id' => 'SecondaryLeft1','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'SecondaryLeft2','id' => 'SecondaryLeft2','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'SecondaryMid1','id' => 'SecondaryMid1','before_widget' => '<div id="%1$s" class="widget secondaryMidColPost %2$s">','after_widget' => '</div>','before_title' => '<h2 class="postTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'SecondaryMid2','id' => 'SecondaryMid2','before_widget' => '<div id="%1$s" class="widget secondaryMidColPost %2$s">','after_widget' => '</div>','before_title' => '<h2 class="postTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'SecondaryRight1','id' => 'SecondaryRight1','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<span class="titleCatName">','after_title' => '</span>',));	
	register_sidebar(array('name' => 'SecondaryRight2','id' => 'SecondaryRight2','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<span class="titleCatName">','after_title' => '</span>',));	
	register_sidebar(array('name' => 'Subnews_1x8','id' => 'Subnews_1x8','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="subnewsEntryTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'Subnews_2x8','id' => 'Subnews_2x8','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="subnewsEntryTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'Subnews_3x8','id' => 'Subnews_3x8','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="subnewsEntryTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'Subnews_4x8','id' => 'Subnews_4x8','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="subnewsEntryTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'Subnews_5x8','id' => 'Subnews_5x8','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="subnewsEntryTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'Subnews_6x8','id' => 'Subnews_6x8','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="subnewsEntryTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'Subnews_7x8','id' => 'Subnews_7x8','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="subnewsEntryTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'Subnews_8x8','id' => 'Subnews_8x8','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h2 class="subnewsEntryTitle">','after_title' => '</h2>',));	
	register_sidebar(array('name' => 'MainP_Sidebar1','id' => 'MainP_Sidebar1','before_widget' => '<div id="%1$s" class="widget sidebarWidget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'MainP_Sidebar2','id' => 'MainP_Sidebar2','before_widget' => '<div id="%1$s" class="widget sidebarWidget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'MainP_Sidebar3','id' => 'MainP_Sidebar3','before_widget' => '<div id="%1$s" class="widget sidebarWidget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'innerWideSidebar_All','id' => 'innerWideSidebar_All','before_widget' => '<div id="%1$s" class="widget wideSidebarWidget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'innernarrowSidebar1','id' => 'innernarrowSidebar1','before_widget' => '<div id="%1$s" class="widget narrowSidebarWidget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="narrowSidebarTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'innernarrowSidebar2','id' => 'innernarrowSidebar2','before_widget' => '<div id="%1$s" class="widget narrowSidebarWidget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="narrowSidebarTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'FooterCategories','id' => 'FooterCategories','before_widget' => '<strong id="%1$s" class="%2$s">','after_widget' => '</strong>','before_title' => '','after_title' => '',));	
	register_sidebar(array('name' => 'FooterPages','id' => 'FooterPages','before_widget' => '<strong id="%1$s" class="%2$s">','after_widget' => '</strong>','before_title' => '','after_title' => '',));	
	register_sidebar(array('name' => 'FooterThemeInfo','id' => 'FooterThemeInfo','before_widget' => '<strong id="%1$s" class="%2$s">','after_widget' => '</strong>','before_title' => '','after_title' => '',));	
	register_sidebar(array('name' => 'Menu_Masthead','id' => 'Menu_Masthead','before_widget' => '','after_widget' => '','before_title' => '','after_title' => '',));	
	register_sidebar(array('name' => 'Menu_Categories','id' => 'Menu_Categories','before_widget' => '','after_widget' => '','before_title' => '','after_title' => '',));	
	register_sidebar(array('name' => 'Menu_Pages','id' => 'Menu_Pages','before_widget' => '','after_widget' => '','before_title' => '','after_title' => '',));	
	register_sidebar(array('name' => 'CustomPageWidget','id' => 'CustomPageWidget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));	
	register_sidebar(array('name' => 'SinglePostWidget','id' => 'SinglePostWidget','before_widget' => '<div id="%1$s" class="widget %2$s">','after_widget' => '</div>','before_title' => '<h3 class="widgetbgTitle">','after_title' => '</h3>',));*/
?>